sudo: false

#branches:
#  only:
#    - master

language: java
jdk:
  - openjdk11
  
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  # fail on any non-zero exit value
  - set -e

script:
  - ./gradlew check
  - ./gradlew assembleDist
  - ./gradlew test
  - ./gradlew run &
  - export pid=$!  
  - echo "marytts running on pid $pid"
  - sleep 30
  - sh .travis/exit_server_and_fail_if_not_running.sh marytts $pid
  - docker build . -t marytts


#from upstream
#before_install:
#  - JAVA_HOME=$(jdk_switcher home openjdk8) ./gradlew
