#!/bin/bash
##########################################################################
# MARY TTS server
##########################################################################

# Set the Mary base installation directory in an environment variable:
BINDIR="`dirname "$0"`"
export MARY_BASE="target/marytts-5.2-SNAPSHOT"


java -showversion -ea -Xms40m -Xmx1g -cp "$BINDIR/../$MARY_BASE/lib/*" -Dmary.base="$BINDIR/../$MARY_BASE" marytts.modules.phonemiser.TrainedLTS $*
